import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { getAuth, GoogleAuthProvider } from "firebase/auth";
import { app, database } from "../../firebase";
import { onValue, ref, set } from "firebase/database";

import styles from "../../styles/Home.module.css";
import Calendar from "../../components/Calendar";

export default function Home() {
  const [username, setUsername] = useState("");
  const router = useRouter();

  useEffect(() => {
    const availability = ref(database, "users/" + router.query.userId);
    onValue(availability, (snapshot) => {
      const data = snapshot.val();
      console.log(data);
    });
  }, []);

  function writeUserData() {
    set(ref(database, "users/" + router.query.userId), {
      username: "name",
      email: "email",
      profile_picture: "imageUrl",
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{username}'s calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Calendar getData={(e) => console.log(e)} />
        <button onClick={writeUserData}>ADD</button>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
          Powered by Vercel
        </a>
      </footer>
    </div>
  );
}
