import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import {} from "firebase/auth";
import { auth } from "../../firebase";

import styles from "./styles.module.css";
import Calendar from "../../components/Calendar";

export default function Home() {
  const [isUserProfile, setIsUserProfile] = useState(false);
  const [isTimeSelectionOpen, setIsTimeSelectionOpen] = useState(false);
  const [isSchedulerInfoOpen, setSchedulerInfoOpen] = useState(false);
  const [date, setDate] = useState<any>();
  const [time, setTime] = useState<any>();
  const router = useRouter();

  function handleSignOut() {
    auth
      .signOut()
      .then((e) => console.log(e))
      .catch((e) => console.log(e));
  }

  useEffect(() => {
    if (
      auth?.currentUser?.uid &&
      auth?.currentUser?.uid === router.query.userId
    ) {
      setIsUserProfile(true);
    }
    console.log(
      auth?.currentUser?.uid && auth?.currentUser?.uid === router.query.userId
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>{isUserProfile ? "My schedule" : "Access Denied"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isUserProfile ? (
        <main className={styles.main}>
          <h1>Your calendar schedule</h1>
          <div className={styles.calendarContainer}>
            <Calendar
              getData={(e) => {
                setDate(e);
                setIsTimeSelectionOpen(true);
              }}
              isTimeSelectionOpen={isTimeSelectionOpen}
            />
            {isTimeSelectionOpen && (
              <div
                className={styles.timeContainer}
                style={{
                  borderRadius: isSchedulerInfoOpen
                    ? "0rem"
                    : "0rem 2rem 2rem 0rem",
                }}
              >
                <h2>Edit time availability</h2>
                <div>
                  <select
                    name=""
                    id=""
                    onChange={(e) => {
                      setTime(e.target.value);
                      setSchedulerInfoOpen(true);
                    }}
                  >
                    <option value="10am">10A.M</option>
                    <option value="12pm">12P.M</option>
                    <option value="14pm">14P.M</option>
                  </select>
                </div>
              </div>
            )}
          </div>
          <button onClick={handleSignOut}>LOG OUT</button>
        </main>
      ) : (
        <h1>403 Forbidden page</h1>
      )}

      <footer className={styles.footer}>
        <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
          Powered by Vercel
        </a>
      </footer>
    </div>
  );
}
