import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { auth } from "../../firebase";

import styles from "./styles.module.css";

export default function Home() {
  const [isUserProfile, setIsUserProfile] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (auth?.currentUser?.uid === router.query.userId) {
      setIsUserProfile(true);
    }
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>{isUserProfile ? "My schedule" : "Access Denied"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isUserProfile ? (
        <main className={styles.main}>
          <h1>USER PROFILE</h1>
        </main>
      ) : (
        <h1>403</h1>
      )}

      <footer className={styles.footer}>
        <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
          Powered by Vercel
        </a>
      </footer>
    </div>
  );
}
